### ISSUE TITLE
【要望】config.sample.php の作成

### ISSUE THREAD

**Issue by nasa114** [jdkfx/hitbot#3]
## 現状の問題点

- 現状、テストを行うにしても必要な情報が全く入っておらず、仮に他の人がテストしたり実行する場合にも不明点が多いため、設定情報の内容をコードを追った上で確認するしか方法がない

## 提案

- 設定ファイルのサンプルファイルを作成する（Issue名に記載のあるファイル名は仮です）

## 補足

- 追加を行う場合はメンテナンスを行う。
- 同時にTwitter連携する場合はトークンなどの情報が必須になるため、このタイミングでサンプルにも追加しておく。（半分予約語として）
  - コンシューマキー
  - コンシューマシークレット
  - アクセストークン
  - アクセストークンシークレット

**Comment by jdkfx** [comment]
### 現状の問題点について

- 確かに必要な情報が確認できない状態ですね。

### 提案について

- 設定ファイルのサンプルファイルの作成はいいと思います。

### 補足に関して

- 補足に関して了解しました。いいと思います。
